apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertint-agent.fullname" . }}
  labels:
    {{- include "alertint-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webhookPort }}
      targetPort: webhook
      protocol: TCP
      name: webhook
    - port: {{ .Values.service.mcpPort }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "alertint-agent.selectorLabels" . | nindent 4 }}
